spring.application.name=training_curriculum_java
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/training_curriculum_java
spring.datasource.username=nono
spring.datasource.password=486028602
spring.flyway.baselineOnMigrate=true